# Generated by Django 6.0.6 on 2026-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_remove_shoe_stock_quantity_alter_shoe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoe_images/'),
        ),
    ]
