# Generated by Django 6.0.6 on 2026-06-06 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shoe'),
        ),
    ]
