# Generated by Django 6.0.6 on 2026-06-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_customer_name_order_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_number', models.CharField(max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.shoe')),
            ],
        ),
    ]
