# Generated by Django 6.0.6 on 2026-06-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_shoe_size_alter_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shoe_images/gallery/')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='store.shoe')),
            ],
        ),
    ]
